using System;

namespace BCMWeb.Core.DTOs
{
    public class CompanyDto
    {
        /// <summary>
        /// Autogenerated company identifier
        /// </summary>
        public long CompanyId { get; set; }
        /// <summary>
        /// Company legal name
        /// </summary>
        public string LegalName { get; set; }
        /// <summary>
        /// Goverment Company Identification
        /// </summary>
        public string GovermentId { get; set; }
        /// <summary>
        /// Company tradename
        /// </summary>
        public string Tradename { get; set; }
        /// <summary>
        /// Administrative address
        /// </summary>
        public string AdministrativeAddress { get; set; }
        /// <summary>
        /// Company state identifier
        /// </summary>
        public long CompanyStateId { get; set; }
        /// <summary>
        /// company state last update 
        /// </summary>
        public DateTime CompanyStateLastUpdate { get; set; }
        /// <summary>
        /// Image logo Url
        /// </summary>
        public string LogoUrl { get; set; }
        /// <summary>
        /// Company start date
        /// </summary>
        public DateTime StartDate { get; set; }
        /// <summary>
        /// Can create process indicator
        /// </summary>
        public bool? CanCreateProcess { get; set; }
        /// <summary>
        /// Can create organizative unit indicator
        /// </summary>
        public bool? CanCreateUO { get; set; }
        /// <summary>
        /// Can create unit work indicator
        /// </summary>
        public bool? CanCreateWorkUnit { get; set; }
        /// <summary>
        /// Can create applications indicator
        /// </summary>
        public bool? CanCreateApps { get; set; }
        /// <summary>
        /// Can create documents indicator
        /// </summary>
        public bool? CanCreateDocs { get; set; }
        /// <summary>
        /// Country identifier
        /// </summary>
        public long? CountryId { get; set; }
        /// <summary>
        /// State identifier
        /// </summary>
        public long? StateId { get; set; }
        /// <summary>
        /// City identifier
        /// </summary>
        public long? CityId { get; set; }

    }
}
